name: Retrieve API Key

on:
  push:
    branches: [ "main" ]

jobs:
  retrieve-api-key:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Retrieve API Key
      run: |
        echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
        echo "API Key successfully retrieved!"

    - name: Use the API Key in your script
      run: |
        # Your script using the API Key
        echo "Using API Key: $API_KEY"